import html
from datetime import datetime

import boto3
from botocore.exceptions import BotoCoreError, ClientError


def send_digest(digest_data: dict, config: dict) -> None:
    sender = config.get("sender", "")
    recipient = config.get("recipient", "")
    region = config.get("aws_region", "us-east-1")

    if not all([sender, recipient]):
        print("[email]    ✗  Missing sender/recipient in config — skipping")
        return

    generated_at = digest_data.get("generated_at", "")
    try:
        dt = datetime.fromisoformat(generated_at)
        date_str = dt.strftime("%A, %B %-d %Y")
    except ValueError:
        date_str = generated_at

    subject = f"Your Morning Reddit Digest - {date_str}"
    body = _build_html(digest_data, date_str)

    try:
        ses = boto3.client("ses", region_name=region)
        ses.send_email(
            Source=sender,
            Destination={"ToAddresses": [recipient]},
            Message={
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {"Html": {"Data": body, "Charset": "UTF-8"}},
            },
        )
        print(f"✓  Sent to {recipient}")
    except ClientError as exc:
        code = exc.response["Error"]["Code"]
        message = exc.response["Error"]["Message"]
        if code == "MessageRejected":
            print(f"✗  SES rejected message: {message}")
            print("   Ensure the sender address is verified in the SES console.")
        elif code in ("InvalidClientTokenId", "AuthFailure"):
            print(f"✗  AWS credentials invalid: {message}")
        else:
            print(f"✗  SES error ({code}): {message}")
    except BotoCoreError as exc:
        print(f"✗  AWS connection error: {exc}")


def _build_html(digest_data: dict, date_str: str) -> str:
    subreddit_blocks = "".join(
        _subreddit_section(sr) for sr in digest_data.get("subreddits", [])
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Morning Digest</title>
</head>
<body style="margin:0;padding:0;background-color:#dae0e6;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"
       style="background-color:#dae0e6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <tr>
    <td style="background-color:#1a1a1b;padding:20px 24px;">
      <h1 style="margin:0;font-size:22px;font-weight:700;color:#ffffff;">
        <span style="color:#FF4500;">r/</span>Morning Digest
      </h1>
      <p style="margin:5px 0 0;font-size:12px;color:#818384;">Generated {html.escape(date_str)}</p>
    </td>
  </tr>
  <tr>
    <td style="padding:24px 16px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
             style="max-width:680px;margin:0 auto;">
        {subreddit_blocks}
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:0 16px 32px;text-align:center;">
      <p style="font-size:11px;color:#878a8c;margin:0;">
        Generated by Reddit Morning Digest
      </p>
    </td>
  </tr>
</table>
</body>
</html>"""


def _subreddit_section(subreddit: dict) -> str:
    name = html.escape(subreddit.get("name", ""))
    post_blocks = "".join(_post_card(p) for p in subreddit.get("posts", []))

    return f"""
<tr>
  <td style="padding:0 0 32px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
           style="margin-bottom:14px;">
      <tr>
        <td style="border-left:4px solid #FF4500;padding:6px 12px;">
          <h2 style="margin:0;font-size:16px;font-weight:700;color:#1c1c1c;">
            <span style="color:#FF4500;">r/</span>{name}
          </h2>
        </td>
      </tr>
    </table>
    {post_blocks}
  </td>
</tr>"""


def _post_card(post: dict) -> str:
    title = html.escape(post.get("title", ""))
    url = html.escape(post.get("url", "#"))
    summary = html.escape(post.get("summary", ""))
    key_insight = html.escape(post.get("key_insight", ""))
    score = f"{post.get('score', 0):,}"
    num_comments = f"{post.get('num_comments', 0):,}"

    insight_block = ""
    if key_insight:
        insight_block = f"""
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
           style="margin:0 0 10px;">
      <tr>
        <td style="background-color:#fff4f0;border-left:3px solid #FF4500;
                   padding:8px 12px;border-radius:0 4px 4px 0;">
          <p style="margin:0;font-size:12px;color:#5a2a00;font-style:italic;line-height:1.45;">
            {key_insight}
          </p>
        </td>
      </tr>
    </table>"""

    return f"""
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"
       style="margin-bottom:10px;background-color:#ffffff;
              border:1px solid #edeff1;border-radius:6px;">
  <tr>
    <td style="padding:16px 20px;">
      <p style="margin:0 0 8px;font-size:15px;font-weight:600;">
        <a href="{url}" style="color:#1c1c1c;text-decoration:none;">{title}</a>
      </p>
      <p style="margin:0 0 10px;font-size:13px;color:#444444;line-height:1.55;">
        {summary}
      </p>
      {insight_block}
      <p style="margin:0;font-size:11px;color:#878a8c;">
        &#9650; {score} upvotes &nbsp;&middot;&nbsp; &#128172; {num_comments} comments
      </p>
    </td>
  </tr>
</table>"""
